version: "3.9"

services:
  frontend:
    build: ./how-much
    container_name: nuxt-frontend
    restart: always
    ports:
      - "3011:3011"
    env_file:
      - .env.frontend
    depends_on:
      - backend
    networks:
      - web

  backend:
    build: ./how-much-backend
    container_name: nest-backend
    restart: always
    ports:
      - "3037:3037"
    env_file:
      - .env.backend
    depends_on:
      - mongo
    networks:
      - web
      - db

  mongo:
    image: mongo:7
    container_name: how-much-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - db

volumes:
  mongo_data:

networks:
  web:
  db:
